apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django-app
  labels:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/instance: {{ .Release.Name }}
