controller:
  serviceType: LoadBalancer
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "2Gi"
  installPlugins:
    - kubernetes:4253.v7700d91739e5
    - workflow-aggregator:600.vb_57cdd26fdd7
    - git:5.2.2
    - configuration-as-code:1836.vccda_4a_122a_a_e

persistence:
  enabled: true
  storageClass: "gp2"
  size: 8Gi

serviceAccount:
  create: true
  name: "jenkins"

rbac:
  create: true
