applications:
  - name: django-app
    project: default
    repoURL: https://github.com/REPLACE_OWNER/REPLACE_REPO.git
    targetRevision: main
    path: Project/charts/django-app
    destinationServer: https://kubernetes.default.svc
    destinationNamespace: django

repositories:
  - url: https://github.com/REPLACE_OWNER/REPLACE_REPO.git
    type: git
